### ISSUE TITLE
[FE] 개발환경 구축

### ISSUE THREAD

**Issue by HelloWorldDogs223** [codestates-seb/seb45_pre_004#1]
개발환경 구축하기
1. 언어 : javacscript
2. 요청 응답 방식 : axios
3. state 관리 : react-redux
4. CSS : Styled Components
5. storybook
6. CRA
7. 배포 : S3
8. npm 사용
9. 코딩 컨벤션
 - 무조건 tab
 - 변수명 : 카멜 케이스
 - 상수명 : 스네이크 케이스
 - 매개변수 1개면 괄호 쓰지 않기
 - 이벤트 핸들러 : on으로 시작
 - 함수 이름 : 명사형
 - export default / export const function_name 형태 사용
 - var 쓰는 것은 지양하기
 - 한 줄의 코드도 괄호를 사용하여 가독성 높이기 (ex. if, for)
 - 함수 위 설명 주석 달아주기
 - styled components 따로 빼기(파일로 구분, 폴더 따로)

**Comment by HyerimKimm** [comment]
- **npm**
    - 설치 : `npm install`
- **styled component**
    
    `npm install --save styled-components@latest`
    
    `import styled from "styled-components"`
    
- **storybook**
    - 설치 : `npx storybook@latest init`
    - 실행 : `npm run storybook`
- **redux**
    - react-redux 설치 : `npm i redux react-redux`
    - redux-devtools 설치`npm i --save-dev redux-devtools-extension`
        
        ```jsx
        import { composeWithDevTools } from 'redux-devtools-extension'; // 리덕스 개발자 도구
        
        const store = createStore(rootReducer, composeWithDevTools()); // 스토어를 만듭니다.
        ```
        
- **router**
    - 설치 : `npm install react-router-dom@^6.3.0`
    - `import { BrowserRouter, Routes, Route, Link, useNavigate } from “react-router-dom”`
- **axios**
    - `npm install axios` or `yarn add axios`
    - `import axios from “axios”;`
